#!/usr/bin/env bash
# Start the CAD Viewer the way the shipped skill tells a user to, and check it answers.
#
# Every other check asks whether the distribution is correctly ASSEMBLED. bundle.sh --check
# compares generated bytes, check-builds.sh inspects the layout. None of them RUN it.
# `npm start` was declared in the runtime's package.json, shipped without its launcher,
# and stayed broken from 0.4.0 to 0.4.18 because no test ever executed the one command the
# skill documents.
#
# The command below is that command. Keep it identical to the one in
# skills/cad-viewer/SKILL.md; if the doc changes, this changes with it. It requires the
# bundled runtime (a real directory, not the dev symlink) — run scripts/bundle/bundle.sh
# first, exactly as test.yml does.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

PORT="${VIEWER_LAUNCH_PORT:-3299}"
HOST="127.0.0.1"
RUNTIME="$REPO_ROOT/skills/cad-viewer/scripts/viewer"

echo "==> CAD Viewer launch smoke test (node scripts/viewer/server/main.mjs)"

if [ -L "$RUNTIME" ]; then
  # A symlinked runtime would smoke-test viewer/ instead of the bundle output.
  echo "FAIL: $RUNTIME is still the development symlink; bundle first." >&2
  exit 1
fi
if [ ! -f "$RUNTIME/server/main.mjs" ]; then
  echo "FAIL: no bundled CAD Viewer runtime at $RUNTIME" >&2
  echo "      Run scripts/bundle/bundle.sh first (test.yml bundles before this step)." >&2
  exit 1
fi
# The built client has to be IN the runtime: its absence is the exact regression this
# guards, and it surfaces as a served page that is 404 rather than as a bad server.
if [ ! -f "$RUNTIME/dist/index.html" ]; then
  echo "FAIL: the bundled runtime carries no built client (dist/index.html missing)" >&2
  exit 1
fi

log="$(mktemp)"
serve_root="$(mktemp -d)"
node "$RUNTIME/server/main.mjs" --root "$serve_root" --host "$HOST" --port "$PORT" > "$log" 2>&1 &
server_pid=$!
disown "$server_pid" 2>/dev/null || true

cleanup() {
  kill "$server_pid" 2>/dev/null || true
  rm -rf "$serve_root"
}
trap cleanup EXIT

status=""
for _ in $(seq 1 30); do
  status="$(curl -s -o /dev/null -m 3 -w '%{http_code}' "http://$HOST:$PORT/" || true)"
  [ "$status" = "200" ] && break
  if ! kill -0 "$server_pid" 2>/dev/null; then
    echo "FAIL: the server exited before serving" >&2
    sed 's/^/    /' "$log" >&2
    exit 1
  fi
  sleep 1
done

if [ "$status" != "200" ]; then
  echo "FAIL: no 200 from http://$HOST:$PORT/ (last status: ${status:-none})" >&2
  sed 's/^/    /' "$log" >&2
  exit 1
fi

# The front end alone is not proof: the server serves a prebuilt bundle, so a live page with
# a dead CAD API still looks fine in a browser until the first model load.
api="$(curl -s -o /dev/null -m 3 -w '%{http_code}' "http://$HOST:$PORT/__cad/server" || true)"
if [ "$api" != "200" ]; then
  echo "FAIL: the page served but /__cad/server returned ${api:-none}" >&2
  sed 's/^/    /' "$log" >&2
  exit 1
fi

# The instance-manager side of the same entrypoint: list must show this server,
# stop must end it.
if ! node "$RUNTIME/server/main.mjs" list | grep -q "port $PORT"; then
  echo "FAIL: 'main.mjs list' did not report the running viewer" >&2
  exit 1
fi
if ! node "$RUNTIME/server/main.mjs" stop --port "$PORT" | grep -q "Stopped CAD Viewer"; then
  echo "FAIL: 'main.mjs stop --port $PORT' did not stop the viewer" >&2
  exit 1
fi

echo "    served / and /__cad/server on port $PORT; list/stop OK"
echo "==> CAD Viewer launch smoke test passed"
