#!/usr/bin/env bash
# Start the CAD Viewer the way the shipped skill tells a user to, and check it answers.
#
# Every other check asks whether the distribution is correctly ASSEMBLED. bundle.sh --check
# compares generated bytes, check-builds.sh inspects the layout. None of them RUN it.
# `npm start` was declared in the runtime's package.json, shipped without its launcher,
# and stayed broken from 0.4.0 to 0.4.18 because no test ever executed the one command the
# skill documents.
#
# The command below is that command. Keep it identical to the one in
# skills/cad-viewer/SKILL.md; if the doc changes, this changes with it. Launching is
# unconditional (the server rolls to a free port and prints the real URL/port), so this
# script chooses no port: it reads the port from the --json line, exactly as an agent
# does. It requires the bundled runtime (a real directory, not the dev symlink) — run
# scripts/bundle/bundle.sh first, exactly as test.yml does.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

HOST="127.0.0.1"
RUNTIME="$REPO_ROOT/skills/cad-viewer/scripts/viewer"

echo "==> CAD Viewer launch smoke test (node scripts/viewer/server/main.mjs)"

if [ -L "$RUNTIME" ]; then
  # A symlinked runtime would smoke-test viewer/ instead of the bundle output.
  echo "FAIL: $RUNTIME is still the development symlink; bundle first." >&2
  exit 1
fi
if [ ! -f "$RUNTIME/server/main.mjs" ]; then
  echo "FAIL: no bundled CAD Viewer runtime at $RUNTIME" >&2
  echo "      Run scripts/bundle/bundle.sh first (test.yml bundles before this step)." >&2
  exit 1
fi
# The built client has to be IN the runtime: its absence is the exact regression this
# guards, and it surfaces as a served page that is 404 rather than as a bad server.
if [ ! -f "$RUNTIME/dist/index.html" ]; then
  echo "FAIL: the bundled runtime carries no built client (dist/index.html missing)" >&2
  exit 1
fi

log="$(mktemp)"
serve_root="$(mktemp -d)"
# The import e2e below spawns `cadgen import` from the server. The bundled
# runtime carries no Python; hand it the repo's interpreter explicitly (the
# soft-dependency contract), cold (no daemon spawned by a smoke test).
export CADGEN_PYTHON="$REPO_ROOT/.venv/bin/python"
export CADGEN_WARM=0
node "$RUNTIME/server/main.mjs" --root "$serve_root" --host "$HOST" --json > "$log" 2>&1 &
server_pid=$!
disown "$server_pid" 2>/dev/null || true

cleanup() {
  kill "$server_pid" 2>/dev/null || true
  rm -rf "$serve_root"
}
trap cleanup EXIT

# The port is an OUTPUT of launch: read it from the {url,port,action} JSON line.
PORT=""
for _ in $(seq 1 30); do
  PORT="$(sed -n 's/^{.*"port":\([0-9]*\).*}$/\1/p' "$log" | tail -1)"
  [ -n "$PORT" ] && break
  if ! kill -0 "$server_pid" 2>/dev/null; then
    echo "FAIL: the server exited before printing its contract" >&2
    sed 's/^/    /' "$log" >&2
    exit 1
  fi
  sleep 1
done
if [ -z "$PORT" ]; then
  echo "FAIL: no {url,port,action} JSON line appeared" >&2
  sed 's/^/    /' "$log" >&2
  exit 1
fi

status=""
for _ in $(seq 1 30); do
  status="$(curl -s -o /dev/null -m 3 -w '%{http_code}' "http://$HOST:$PORT/" || true)"
  [ "$status" = "200" ] && break
  sleep 1
done
if [ "$status" != "200" ]; then
  echo "FAIL: no 200 from http://$HOST:$PORT/ (last status: ${status:-none})" >&2
  sed 's/^/    /' "$log" >&2
  exit 1
fi

# The front end alone is not proof: the server serves a prebuilt bundle, so a live page with
# a dead CAD API still looks fine in a browser until the first model load.
api="$(curl -s -o /dev/null -m 3 -w '%{http_code}' "http://$HOST:$PORT/__cad/server" || true)"
if [ "$api" != "200" ]; then
  echo "FAIL: the page served but /__cad/server returned ${api:-none}" >&2
  sed 's/^/    /' "$log" >&2
  exit 1
fi

# Launch idempotence: relaunching the same root at the same version must REUSE the
# running viewer (same port, action:"reused"), not spawn a second instance.
reuse_json="$(node "$RUNTIME/server/main.mjs" --root "$serve_root" --host "$HOST" --json | grep '^{' | tail -1)"
if ! printf '%s' "$reuse_json" | grep -q '"action":"reused"'; then
  echo "FAIL: relaunching the same root did not reuse the running viewer: $reuse_json" >&2
  exit 1
fi
if ! printf '%s' "$reuse_json" | grep -q "\"port\":$PORT"; then
  echo "FAIL: reuse reported a different port than the running viewer: $reuse_json" >&2
  exit 1
fi

# End-to-end import FROM THE BUNDLE: a raw STEP in the served root goes
# needs-build -> POST build (spawns `cadgen import`) -> ready with a real
# package. The bundled runtime has no Python of its own; the smoke run
# provides the repo venv via CADGEN_PYTHON (set at server launch above,
# see the env block) — the same soft-dependency contract users get. The
# fixture is deliberately non-LFS (CI checks out without LFS).
FIXTURE="$REPO_ROOT/models/fixtures/import-smoke.step"
if ! head -1 "$FIXTURE" | grep -q "ISO-10303-21"; then
  echo "FAIL: import fixture is not STEP text (LFS pointer?): $FIXTURE" >&2
  exit 1
fi
cp "$FIXTURE" "$serve_root/smoke.step"
step_url="http://$HOST:$PORT/__cad/artifact?file=smoke.step"
status_json="$(curl -s -m 10 "$step_url")"
if ! printf '%s' "$status_json" | grep -q '"needs-build"'; then
  echo "FAIL: raw STEP did not report needs-build: $status_json" >&2
  exit 1
fi
if ! printf '%s' "$status_json" | grep -q '"stepImport":true'; then
  echo "FAIL: raw STEP status did not offer the import: $status_json" >&2
  exit 1
fi
# The import pays one cold interpreter + OCP start; give it a real timeout.
build_json="$(curl -s -m 120 -X POST -H 'x-cadgen-viewer: 1' "$step_url")"
if ! printf '%s' "$build_json" | grep -q '"ok":true'; then
  echo "FAIL: cadgen import build did not succeed: $build_json" >&2
  exit 1
fi
if [ ! -f "$serve_root/__cadgen__/models/smoke.step/assembly.json" ]; then
  echo "FAIL: import reported ok but wrote no package descriptor" >&2
  exit 1
fi
status_json="$(curl -s -m 10 "$step_url")"
if ! printf '%s' "$status_json" | grep -q '"ready"'; then
  echo "FAIL: imported STEP did not settle ready: $status_json" >&2
  exit 1
fi

# The instance-manager side of the same entrypoint: list must show this server,
# stop must end it.
if ! node "$RUNTIME/server/main.mjs" list | grep -q "port $PORT"; then
  echo "FAIL: 'main.mjs list' did not report the running viewer" >&2
  exit 1
fi
if ! node "$RUNTIME/server/main.mjs" stop --port "$PORT" | grep -q "Stopped CAD Viewer"; then
  echo "FAIL: 'main.mjs stop --port $PORT' did not stop the viewer" >&2
  exit 1
fi

echo "    served / and /__cad/server on rolled port $PORT; cadgen import e2e OK; reuse/list/stop OK"
echo "==> CAD Viewer launch smoke test passed"
