#!/usr/bin/env bash
# Start the CAD Viewer the way the shipped skill tells a user to, and check it answers.
#
# Every other check asks whether the distribution is correctly ASSEMBLED. bundle.sh --check
# compares generated bytes, check-builds.sh inspects the layout. None of them RUN it.
# `npm start` was declared in the runtime's package.json, shipped without its launcher,
# and stayed broken from 0.4.0 to 0.4.18 because no test ever executed the one command the
# skill documents.
#
# The command below is that command. Keep it identical to the one in
# skills/cad-viewer/SKILL.md; if the doc changes, this changes with it. Launching is
# unconditional (the server rolls to a free port and prints the real URL/port), so this
# script chooses no port: it reads the port from the --json line, exactly as an agent
# does. It requires the bundled runtime (a real directory, not the dev symlink) — run
# scripts/bundle/bundle.sh first, exactly as test.yml does.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

HOST="127.0.0.1"
# VIEWER_RUNTIME_DIR points the smoke test at a runtime bundled somewhere else.
# It is not decoration: bundling IN PLACE replaces the development symlink at
# the default path with a real directory, so a developer who runs this script
# has to repair their checkout with scripts/dev/setup-symlinks.sh afterwards.
# Bundling into a scratch directory and naming it here costs nothing and leaves
# the tree alone. CI always uses the default, because test.yml bundles in place
# on a throwaway runner.
RUNTIME="${VIEWER_RUNTIME_DIR:-$REPO_ROOT/skills/cad-viewer/scripts/viewer}"

echo "==> CAD Viewer launch smoke test (\$PYTHON scripts/viewer/server/main.py)"

if [ -L "$RUNTIME" ]; then
  # A symlinked runtime would smoke-test viewer/ instead of the bundle output.
  echo "FAIL: $RUNTIME is still the development symlink; bundle first." >&2
  exit 1
fi
if [ ! -f "$RUNTIME/server/main.py" ]; then
  echo "FAIL: no bundled CAD Viewer runtime at $RUNTIME" >&2
  echo "      Run scripts/bundle/bundle.sh first (test.yml bundles before this step)." >&2
  exit 1
fi
# The built client has to be IN the runtime: its absence is the exact regression this
# guards, and it surfaces as a served page that is 404 rather than as a bad server.
if [ ! -f "$RUNTIME/dist/index.html" ]; then
  echo "FAIL: the bundled runtime carries no built client (dist/index.html missing)" >&2
  exit 1
fi

log="$(mktemp)"
serve_root="$(mktemp -d)"
# The server IS a Python process now: this is the interpreter that plays the
# role of "the one that installed skills/cad-viewer/requirements.txt", which is
# the only door cadgen comes through. There is no CADGEN_PYTHON any more.
#
# Resolution FALLS BACK instead of demanding a repo venv, because there are two
# venv-less callers and both are ordinary:
#
#   * GitHub Actions. .github/actions/setup-deps uses actions/setup-python and
#     installs requirements-dev.txt into the interpreter on PATH; no .venv is
#     ever created. Hard-requiring $REPO_ROOT/.venv/bin/python made this step
#     fail before it started anything, on every pull request.
#   * A lightweight worktree. CONTRIBUTING's recipe deliberately does not copy
#     .venv, so a developer running this by hand hit the identical wall.
#
# Setting VIEWER_PYTHON in test.yml would have fixed only the first. The
# fallback fixes both, and uses the same order scripts/test/common.sh already
# uses for every other Python runner in this repo, so "which interpreter do the
# tests use" has one answer.
#
# The first candidate that can import cadgen wins, and cadgen is REQUIRED: the
# end-to-end import below is most of what this script proves, so a machine that
# cannot run it should say so here in one line rather than 60 seconds later
# inside a POST that returns ok:false. An explicit VIEWER_PYTHON is never
# second-guessed — it is used, or the script fails naming it.
pick_interpreter() {
  local candidates=()
  if [ -n "${VIEWER_PYTHON:-}" ]; then
    candidates=("$VIEWER_PYTHON")
  else
    candidates=("$REPO_ROOT/.venv/bin/python" python3 python)
  fi

  local candidate resolved
  FOUND_INTERPRETER=""
  for candidate in "${candidates[@]}"; do
    resolved="$(command -v "$candidate" 2>/dev/null || true)"
    [ -n "$resolved" ] && [ -x "$resolved" ] || continue
    [ -n "$FOUND_INTERPRETER" ] || FOUND_INTERPRETER="$resolved"
    if "$resolved" -c 'import importlib.util, sys; sys.exit(0 if importlib.util.find_spec("cadgen") else 1)' \
        >/dev/null 2>&1; then
      PYTHON="$resolved"
      return 0
    fi
  done
  return 1
}

if ! pick_interpreter; then
  if [ -n "${VIEWER_PYTHON:-}" ]; then
    echo "FAIL: VIEWER_PYTHON=$VIEWER_PYTHON cannot run, or cannot import cadgen." >&2
  elif [ -z "$FOUND_INTERPRETER" ]; then
    echo "FAIL: no Python interpreter found (tried $REPO_ROOT/.venv/bin/python, python3, python)." >&2
    echo "      Set VIEWER_PYTHON to the one that installed requirements-dev.txt." >&2
    exit 1
  else
    echo "FAIL: cadgen is not importable from $FOUND_INTERPRETER." >&2
  fi
  echo "      This test imports a real STEP end to end, so the launching interpreter" >&2
  echo "      needs cadgen: pip install -r requirements-dev.txt, or set VIEWER_PYTHON." >&2
  exit 1
fi
echo "    interpreter: $PYTHON"
# Cold: a smoke test spawns no build daemon.
export CADGEN_DAEMON=0
# Isolated store: content keying would otherwise resolve the fixture against
# the developer's real cache and skip the import this smoke test exists to run.
export CADGEN_CACHE_DIR="$(mktemp -d)"
# The launcher has no directory flag: the cwd IS the served directory, so the
# launch cd's there first — exactly as SKILL.md instructs. `exec` makes the
# subshell BECOME the python process, so $! is the server's pid.
(cd "$serve_root" && exec "$PYTHON" "$RUNTIME/server/main.py" --host "$HOST" --json) > "$log" 2>&1 &
server_pid=$!
disown "$server_pid" 2>/dev/null || true

cleanup() {
  kill "$server_pid" 2>/dev/null || true
  rm -rf "$serve_root" "$CADGEN_CACHE_DIR"
}
trap cleanup EXIT

# The port is an OUTPUT of launch: read it from the {url,port,action} JSON line.
PORT=""
for _ in $(seq 1 30); do
  PORT="$(sed -n 's/^{.*"port":\([0-9]*\).*}$/\1/p' "$log" | tail -1)"
  [ -n "$PORT" ] && break
  if ! kill -0 "$server_pid" 2>/dev/null; then
    echo "FAIL: the server exited before printing its contract" >&2
    sed 's/^/    /' "$log" >&2
    exit 1
  fi
  sleep 1
done
if [ -z "$PORT" ]; then
  echo "FAIL: no {url,port,action} JSON line appeared" >&2
  sed 's/^/    /' "$log" >&2
  exit 1
fi

status=""
for _ in $(seq 1 30); do
  status="$(curl -s -o /dev/null -m 3 -w '%{http_code}' "http://$HOST:$PORT/" || true)"
  [ "$status" = "200" ] && break
  sleep 1
done
if [ "$status" != "200" ]; then
  echo "FAIL: no 200 from http://$HOST:$PORT/ (last status: ${status:-none})" >&2
  sed 's/^/    /' "$log" >&2
  exit 1
fi

# The front end alone is not proof: the server serves a prebuilt bundle, so a live page with
# a dead CAD API still looks fine in a browser until the first model load.
api="$(curl -s -o /dev/null -m 3 -w '%{http_code}' "http://$HOST:$PORT/__cad/server" || true)"
if [ "$api" != "200" ]; then
  echo "FAIL: the page served but /__cad/server returned ${api:-none}" >&2
  sed 's/^/    /' "$log" >&2
  exit 1
fi

# Launch idempotence: relaunching from the same directory at the same version must
# REUSE the running viewer (same port, action:"reused"), not spawn a second instance.
reuse_json="$(cd "$serve_root" && "$PYTHON" "$RUNTIME/server/main.py" --host "$HOST" --json | grep '^{' | tail -1)"
if ! printf '%s' "$reuse_json" | grep -q '"action":"reused"'; then
  echo "FAIL: relaunching the same root did not reuse the running viewer: $reuse_json" >&2
  exit 1
fi
if ! printf '%s' "$reuse_json" | grep -q "\"port\":$PORT"; then
  echo "FAIL: reuse reported a different port than the running viewer: $reuse_json" >&2
  exit 1
fi

# End-to-end import FROM THE BUNDLE: a raw STEP in the served root goes
# needs-build -> POST build (cadgen's compile entry point, called in the
# server's own worker) -> ready with a real package. cadgen reaches the server
# only by being importable from $PYTHON — the same soft-dependency contract
# users get from requirements.txt. The fixture is deliberately non-LFS (CI
# checks out without LFS).
FIXTURE="$REPO_ROOT/models/examples/imported/import-smoke.step"
if ! head -1 "$FIXTURE" | grep -q "ISO-10303-21"; then
  echo "FAIL: import fixture is not STEP text (LFS pointer?): $FIXTURE" >&2
  exit 1
fi
cp "$FIXTURE" "$serve_root/smoke.step"
step_url="http://$HOST:$PORT/__cad/artifact?file=smoke.step"
status_json="$(curl -s -m 10 "$step_url")"
if ! printf '%s' "$status_json" | grep -q '"needs-build"'; then
  echo "FAIL: raw STEP did not report needs-build: $status_json" >&2
  exit 1
fi
if ! printf '%s' "$status_json" | grep -q '"stepImport":true'; then
  echo "FAIL: raw STEP status did not offer the import: $status_json" >&2
  exit 1
fi
# The import pays one cold interpreter + OCP start; give it a real timeout.
build_json="$(curl -s -m 120 -X POST -H 'x-cadgen-viewer: 1' "$step_url")"
if ! printf '%s' "$build_json" | grep -q '"ok":true'; then
  echo "FAIL: cadgen step build did not succeed: $build_json" >&2
  exit 1
fi
# Store-primary: the package lands in the (isolated) store keyed by content.
if ! ls "$CADGEN_CACHE_DIR"/packages/*/assembly.json > /dev/null 2>&1; then
  echo "FAIL: import reported ok but wrote no package descriptor in the store" >&2
  exit 1
fi
status_json="$(curl -s -m 10 "$step_url")"
if ! printf '%s' "$status_json" | grep -q '"ready"'; then
  echo "FAIL: imported STEP did not settle ready: $status_json" >&2
  exit 1
fi

# The instance-manager side of the same entrypoint: list must show this server,
# stop must end it.
if ! "$PYTHON" "$RUNTIME/server/main.py" list | grep -q "port $PORT"; then
  echo "FAIL: 'main.py list' did not report the running viewer" >&2
  exit 1
fi
if ! "$PYTHON" "$RUNTIME/server/main.py" stop --port "$PORT" | grep -q "Stopped CAD Viewer"; then
  echo "FAIL: 'main.py stop --port $PORT' did not stop the viewer" >&2
  exit 1
fi

echo "    served / and /__cad/server on rolled port $PORT; cadgen step build e2e OK; reuse/list/stop OK"
echo "==> CAD Viewer launch smoke test passed"
